### ISSUE TITLE
Houdini USD Render Rop publish when DCM is enabled

### ISSUE THREAD

**Issue by krishnaavril** [ynput/ayon-houdini#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

* When Publishing using "USD Render Rop" -> If the DCM(DeepCameraMap) was enabled, its publishing the dcm, leaving the beauty

*If the DCM is off, its publishing the beauty(this is good)

![image](https://github.com/user-attachments/assets/bbb26aeb-becb-49ba-b904-13eb0720870b)

### Expected Behavior:

* Should publish DCM as a seperate render layer

(adding beauty in DCM is possible, however it increases the files size dratically)

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

Publish the karma renders withDCM using USDRenderRop (You will not see bty)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
Thanks for the report.

The logic that "identifies" what the AOV name is - is defined [here](https://github.com/ynput/ayon-houdini/blob/fcab5ff338e0a0cc4f8ae92e8e99143d1a80d5d1/client/ayon_houdini/plugins/publish/collect_render_products.py#L147-L188).

For context: [DCM](https://www.sidefx.com/docs/houdini/render/dcm.html) are Deep Camera Maps.

What are the rendervars specified for the DCM render product? I have myself not used DCM before - what's the usual use case to render it? And especially, why are you rendering BOTH the DCM and the and the regular render? Isn't the DCM essentially the regular render but WITH deep data?

---

A workaround for now would be to use two USD render ROPs, one for the DCM, one for the other.

**Comment by krishnaavril** [comment]
Thanks for the comment @BigRoy 

Studios especially in Highend- live action-VFX completely works with deep data it is the very essential thing. In general, we provide general EXR and deep EXR separately coz of
~ Deep is very heavy in size. depending on scene, adding AOVs inside deep will be lot lot bigger. So we render both separately and compositors will use deep only when required(to optimize the nuke script), so it's better to avoid AOVs in deep and provide the necessary passes in EXR, this technique is vastly used by major companies.

```What are the rendervars specified for the DCM render product?```
No rendervars for better workflow

```why are you rendering BOTH the DCM and the and the regular render?```
We can't render deep alone, there will be always beauty it renders with it

```A workaround for now would be to use two USD render ROPs, one for the DCM, one for the other.```
This is great suggestion, but the render time will be increased.


We managed to change our OTL in a way that bty and DCM split and gives two different outputs for publishing
The bottleneck again is nuke doesn';t have option to recognise the deep layers loading through ayon 
![image](https://github.com/user-attachments/assets/06586910-77c9-4fb3-a364-d247f1057afd)

**Comment by BigRoy** [comment]
> `What are the rendervars specified for the DCM render product?`
> No rendervars for better workflow

A render product ALWAYS has rendervars, otherwise there's nothing to render. ;) Looking at where the logic fails, I suspect it definitely has more than one render var. So the question remains, which?

> We can't render deep alone, there will be always beauty it renders with it

Isn't the "deep" embedded INTO the file? So yes - it always renders the AOVs along. In this case, aren't you better off _just_ rendering the DCM sequence, and if you want a lighter sequence without deep - to then remove the deep metadata?

> We managed to change our OTL in a way that bty and DCM split and gives two different outputs for publishing

Sorry, did it solve this error? And if so, how?

**Comment by krishnaavril** [comment]
We avoid render vars in Deep, deepexr will carry only deep data - coz of file size issues with deep
General exrs carry all the render vars incl utilities,crypto etc

```Sorry, did it solve this error? And if so, how?```
In our own render OTL, we segregated Bty and deep with different render settings node(each have there own render products) and they both output two extra streams in the OTL. they will used for publishing only. (We are hoping this is a temporary solution until the deep gets properly published through the ayon and loads properly in nuke)

**Comment by BigRoy** [comment]
> A render product ALWAYS has rendervars, otherwise there's nothing to render. ;)

Just want to correct myself on this - it seems your scene is explicitly clearing all rendervars but is still generating some output. Odd, but apparently that's how it is with your DCM use case.
