### ISSUE TITLE
Asset Lop doesn't show available products to load amd also wrong product type when loading alembic

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-houdini#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Asset lop uses project, folder path and product type to populate product drop down menu.
![image](https://github.com/ynput/ayon-houdini/assets/20871534/ba63ce3c-9e6e-4806-ba9d-29eef3e71c8e)

### Expected Behavior:

It should show more products.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Load abc with asset lop 
2. click on the product drop down menu.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by MustafaJafar** [comment]
Considered solutions: 
Turn product type into a drop down menu.
Update product type when loading different a product.

**Comment by BigRoy** [comment]
So technically what it does currently is good as expected - it's just that the product type should be changeable? :)

**Comment by MustafaJafar** [comment]
> it's just that the product type should be changeable? :)
This is one thing. 

Another thing is to consider other product types in the drop down menu. e.g. cameras, model and pointcache.
which requires updating the drop down menu of products to filter out products.
but this is hard because it will add one more step, filtering based on representation takes product version as argument. 

```
product
     version 
           representation
```
