### ISSUE TITLE
Layer Muting fails with USD Asset Resolver enabled

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-houdini#151]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior

Muting USD layers of the asset contribution workflow seems to fail with asset resolvers enabled. It just doesn't mute that layer or its children. Disabling e.g. the `ayon-usd` addon resolves the issue. It may have to do with the usage of `:SDF_FORMAT_ARGS:` in certain file paths in the contribution workflow.

## Expected Behavior

Muting layers should work, and be super easy.

### Steps To Reproduce:

Enable `ayon-usd` addon with the USD Asset Resolver enabled.

3. Publish USD asset with model and look layers
4. Create AYON Mute Layers node
5. Set it to mute the look layer.
6. The materials remain (the layer is not muted)

**Comment by BigRoy** [comment]
@Lypsolon was kind enough to do a test run and reproduce this.

Here's his setup:

![Image](https://github.com/user-attachments/assets/bdda2386-057f-4fde-a2c0-446c6b21e2aa)

This layer muting works:

![Image](https://github.com/user-attachments/assets/f5690906-90cb-4bee-97e1-8ff4162eaa09)

But this does not:

![Image](https://github.com/user-attachments/assets/24bbcf7e-aaf6-48a4-b51c-03970b1af78d)

It seems to NOT mute the child layer (and since I suppose that should not be possible to include a child layer if the parent is muted I assume it's not actually muting that layer even though it's set to 'muted' visually in Houdini).

I do think it's:
- An actual USD bug because I have no idea how muting a layer should still allow the child layer to be included. 
- Or - Houdini found the layer in the "muted layer paths" (and hence made it purple) but it's not actually the correct path for layer muting that should be applied to USD itself - so according to the USD composition, it's not actually muted. IF so, then that's a Houdini bug.
- Or our AYON USD resolver happens to be doing something with the filepaths that is technically incorrect and returns invalid paths or alike breaking the logic here.

**Comment by BigRoy** [comment]
Reassigned to @Lypsolon since it's likely easier for him to investigate from the resolver itself. Plus I've heard he just really likes issues! 🥇

**Comment by Lypsolon** [comment]
@BigRoy 
i tested this issue with the new Resolvers we have in `https://lake.ayon.cloud/repositories/ayon-usd/objects?ref=Nightly&path=` 
i believe this issue was cause because of the removal of the SDF_FORMAT_ARGS then new system now appends them at the end again. 

i tested this with "Normal" paths and with URIs and both look like they work. 
this will now also be tested in the internal Usd Project.

**Comment by BigRoy** [comment]
Feel free to close when fix is merged and released.

**Comment by Lypsolon** [comment]
this has been solved and tested in the internal AyonUsd Project where the issue was first found. 

the issue was that the _CreateIdentifier function removed the SDF_ARGS from the input path and thereby created an identifier for an wrong layer.
