### ISSUE TITLE
publish existing caches

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-houdini#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Render Targets is supported with render but not cache. 
![image](https://github.com/ynput/ayon-houdini/assets/20871534/70ebadaa-944a-4194-b4a5-055655f9898e)

### How would you imagine the implementation of the feature?

Render targets should be supported with cache

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by BigRoy** [comment]
Yes, I'd like Use Existing Frames for all product types in Houdini if we can. (Although the USD extraction logic may make that tricky potentially because it's the ROP node that does some path remapping)

**Comment by antirotor** [comment]
Is this related to [#6](https://github.com/ynput/ayon-houdini/issues/6)

**Comment by johhnry** [comment]
Hi, we are interested in this behavior! Being able to publish a cache that was already computed without having to recompute it again. Maybe for now we can have a single checkbox saying "Use existing cache" that skips the file cache creation again?

**Comment by krishnaavril** [comment]
Hey! Any thoughts on this one? just curious if any wip is available to test

This could potentially save tons of size in servers!

**Comment by krishnaavril** [comment]
I have made a pull request #154
