### ISSUE TITLE
Houdini: Unable to review/Render using Lopimportcamera

### ISSUE THREAD

**Issue by krishnaavril** [ynput/ayon-houdini#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

<img width="1529" alt="image" src="https://github.com/ynput/OpenPype/assets/61413765/60aa286d-06f2-4d50-a7e7-bfe3f266821e">

Currently OP is publishing without errors using SOP level import camera. Its thowing error when loading the LOP camera

### How would you imagine the implementation of the feature?

The OP should successfully publish, using Lopimportcamera SOP node as well

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[OP-6365](https://app.clickup.com/t/863h6y90b)]

**Comment by MustafaJafar** [comment]
Related but doesn't solve the issue. 
Publishing render supports marking as review.
![image](https://github.com/ynput/ayon-houdini/assets/20871534/39ad2f18-d914-4e81-8502-deba7b36a2d7)
