### ISSUE TITLE
Support Houdini workfile templates

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-houdini#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Support Templated workfile build similar to Nuke and Maya.

### How would you imagine the implementation of the feature?

..

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by BigRoy** [comment]
Just wanted to remark the Houdini 20.5 feature called **[Recipes](https://www.sidefx.com/docs/houdini20.5/network/recipes.html)**

- https://www.sidefx.com/docs/houdini20.5/network/recipes.html
- https://www.sidefx.com/products/whats-new-in-h205/

I wonder if it'd be worth it to investigate if any of that may be relevant to "templates" for the workfiles.
