### ISSUE TITLE
Houdini BGEO.SC Publish extension is missing

### ISSUE THREAD

**Issue by krishna8008** [ynput/ayon-houdini#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Publish in Ayon, its exporting the cache without the extension
<img width="1851" alt="image" src="https://github.com/ynput/ayon-houdini/assets/61413765/8dfa44c4-a530-411c-a29a-dda25522695a">

### Expected Behavior:

The extension should be written in the filename

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

Publish the BGEO in houdini single frame

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
@krishna8008 what completed this?

**Comment by krishna8008** [comment]
Hey @BigRoy  this issue was not there when we changed the project settings to a single frame in Ayon.

When it was set to full frame range and tried to publish a single frame, the extension was missing. When publishing with proper settings everything is good

**Comment by BigRoy** [comment]
I see - so the issue STILL exists when publishing a single frame, or has that been resolved recently as well?
