### ISSUE TITLE
Houdini: USD Render wrong colorspace

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-houdini#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:
```
"colorspaceData": {
    "colorspace": "",
    "config": {
        "path": "C:/Users/.....Documents/houdini20.0/ocio/houdini-config-v1.0.0_aces-v1.3_ocio-v2.1.ocio",
        "template": "C:/Users/..../Documents/houdini20.0/ocio/houdini-config-v1.0.0_aces-v1.3_ocio-v2.1.ocio"
    },
    "display": "sRGB - Display",
    "view": "ACES 1.0 - SDR Video"
},
```
Which seems to be the wrong OCIO config?
Also, it reports "colorspace": null for the instance itself, which makes me think it's also not correctly detecting the colorspace of the output product.
You're using Karma XPU?
Yes.

### Expected Behavior:

.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

..

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
> ```
> "colorspaceData": {
>     "colorspace": "",
>     "config": {
>         "path": "C:/Users/.....Documents/houdini20.0/ocio/houdini-config-v1.0.0_aces-v1.3_ocio-v2.1.ocio",
>         "template": "C:/Users/..../Documents/houdini20.0/ocio/houdini-config-v1.0.0_aces-v1.3_ocio-v2.1.ocio"
>     },
>     "display": "sRGB - Display",
>     "view": "ACES 1.0 - SDR Video"
> },
> ```
> 
> 
>     
>   
> 
> Which seems to be the wrong OCIO config?

So... this does actually work currently:

```python
>>> get_color_management_preferences()
{'config': 'P:/Resources/colorspace/studio-config-v1.0.0_aces-v1.3_ocio-v2.1/studio-config-v1.0.0_aces-v1.3_ocio-v2.1.ocio', 'display': 'sRGB - Display', 'view': 'Un-tone-mapped'}
```

Anyway, will look into collecting the colorspace of the renderlayers, etc.

**Comment by BigRoy** [comment]
Also, it's defaulting to the default display/view colorspace: https://github.com/ynput/ayon-houdini/blob/c6c52fd8c94d83fb31ffe5576a4cd7cd10473509/client/ayon_houdini/plugins/publish/collect_usd_render.py#L86

Which gets the defaults from here:
https://github.com/ynput/ayon-houdini/blob/7c71563ab7fb574bf41fde5a52ac6fc1c400e659/client/ayon_houdini/api/colorspace.py#L38-L56
