### ISSUE TITLE
Render Setup Workflow alternative for Houdini

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-houdini#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

In Maya, there is "Render Setup" workflow, serializing settings in Render Settings and publishing them as JSON files with ability to load them again.

Something similar can be done for Houdini too, from simple serialization of subset of values on ROP node to HDA based solution.

As first step, simple value serialization can be enough.

### How would you imagine the implementation of the feature?

..

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

Internal Ticket Number: AY-6061

**Comment by MustafaJafar** [comment]
I've found out that Houdini 20.5 supports a great solution for this one.

https://www.sidefx.com/docs/houdini/network/recipes.html
See it in action:

https://www.youtube.com/watch?v=o1xg202Rbg8

**Comment by BigRoy** [comment]
Want to add that in USD this has much less importance because all of this is just USD data that can just be saved and loaded.

**Comment by MustafaJafar** [comment]
> Want to add that in USD this has much less importance because all of this is just USD data that can just be saved and loaded.

Thanks for the note.. I believe we may discuss this furtherly to come up with better ideas for different use cases but lets leave it for another time 🏖️ ⚽ .

**Comment by antirotor** [comment]
Closing this now as this is solved by presets in houdini.
